### ISSUE TITLE
Need APIs for validation rewards and storage fee of a blobber

### ISSUE THREAD

**Issue by sagchain** [0chain/0chain#1646] opened 2022-09-08 09:49 UTC
For Validation rewards and transactional revenue we will need APIs, currently we only seem to have it for block and staking rewards.

More context here: https://0chain.slack.com/archives/C03UX0USFQC/p1662054872417119

**Comment by lawRathod** [comment] 2022-09-09 08:15
How would transactional revenue be calculated? What does this information represent?

**Comment by sagchain** [comment] 2022-09-09 18:12
Transactional revenue/fee is storage fee paid by the users for availing the storage on the blobber server.

**Comment by Sriep** [comment] 2022-09-12 09:42
We currently have a way of distigushing different reward types. If this is what is being requested, we should open an issue to implemented montoring rewards by reward type. We currently don't keep this information, so will need some work to implement.

**Comment by sagchain** [comment] 2022-09-13 02:58
Yes, we need that information

**Comment by manasnisar** [comment] 2022-11-10 07:53
@dabasov Is the `storage fee` here the same as `blobber_write_price`? If yes, we already have that. Regarding the `validation rewards`, can you clarify?

**Comment by dabasov** [comment] 2022-11-30 09:16
@sagchain explain what is validation rewards and transactional revenue in terms of system we never used this wording before

**Comment by sagchain** [comment] 2022-12-07 06:42
There are 3 types of rewards that a blobber can get: Storage income, Validation reward and block reward, we want to show this information separately along with total rewards for a blobber which is a summation of all 3

**Comment by manasnisar** [comment] 2023-02-11 02:30
Duplicate of https://github.com/0chain/0box/issues/218

**Closed as completed by manasnisar** 2023-02-11 02:30 UTC
Labels: api
