### ISSUE TITLE
DecodeDelegatePools

### ISSUE THREAD

**Issue by kirillt** [0chain/0chain#114] opened 2021-03-16 09:46 UTC
We potentially have a bug in `minersc/models.go: func DecodeDelegatePools`. Methods `getMinersList` and `getShardersList` return structure `MinersList` which is a wrapper around `SimpleNode` and also have fields with Pending/Active/Deleting pools. Those pools are not initialized when we are calling `getMinersList`, so we need to query smart contract again.

We also might not need these fields in this structure at all. We can query pools explicitly in rare cases we need them.

**Comment by andrenerd** [comment] 2021-06-01 00:53
The issues was reported prior significant changes in the code (was done by @Sriep on Mar26). It makes the description non relevant.  

@kirillt Please, retest it. or close it.

**Comment by guruhubb** [comment] 2021-06-05 22:41
Since @kirillt is no longer here, can you @andrenerd  retest and close this issue

**Comment by andrenerd** [comment] 2021-06-07 02:18
Checked. Looks like the issue is gone after the update.

There is no the invalid fields in the returned structure anymore. Basically, as it was proposed by Kirill when he wrote: "We also might not need these fields in this structure at all."

PS.
attached the screenshots.
https://seven.devnet-0chain.net/sharder01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d9/getMinerList
https://seven.devnet-0chain.net/sharder01/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d9/getSharderList

<img width="1113" alt="Screenshot 2021-06-07 at 04 12 55" src="https://user-images.githubusercontent.com/3892914/120950586-5e156d00-c747-11eb-9d40-3053130e8da8.png">


<img width="1117" alt="Screenshot 2021-06-07 at 04 13 17" src="https://user-images.githubusercontent.com/3892914/120950598-65d51180-c747-11eb-940b-33674b57a2fa.png">

**Closed by andrenerd** 2021-06-07 02:18 UTC
