### ISSUE TITLE
Recover wallet returns random wallet for randomly invented mnemonic

### ISSUE THREAD

**Issue by webPlayer7** [0chain/0chain#571] opened 2021-10-06 15:30 UTC
I tried to recover the wallet and enter the random secret phrase, and it returns with a random wallet with the input secret phrase.
I am not sure it is originally designed like this flow or it should show an error for the non-existing secret phrase.

**Comment by shaktals** [comment] 2021-10-06 15:37
I'd think it should return en error if a wallet with the provided mnemonic does not exist.

**Comment by shaktals** [comment] 2021-10-13 14:58
@Sriep @m-s-a-c can you indicate someone to help us here?

**Comment by Sriep** [comment] 2021-10-25 14:53
How did you `recover the wallet and enter the random secret phrase`? Did you use a tool like `zwallet`, or maybe send a transaction somewhere using `curl`? Please give the command sent.

**Comment by webPlayer7** [comment] 2021-10-25 17:46
I tried to recover wallet using block-explorer @Sriep

**Comment by guruhubb** [comment] 2021-10-25 18:51
@shaktals @JordanMicle2019 please make sure you try with zwalletcli and zboxcli before posting issues. Its mandatory for all developers to know how to use cli and also to have a blockchain running on their laptop to look at the issue locally if needed.

**Comment by shaktals** [comment] 2021-10-27 13:04
> @shaktals @JordanMicle2019 please make sure you try with zwalletcli and zboxcli before posting issues. Its mandatory for all developers to know how to use cli and also to have a blockchain running on their laptop to look at the issue locally if needed.

Yeap, always do. In this case it's not an API failing when it should work, but the reverse. It seems to be mistakenly working when it shouldn't. 

So CLI would only help here if it performs a check of the mnemonic/secret phrase against a different API before trying to recover it. That really didn't cross my mind before, but I think there isn't such an endpoint yet, right? Anyways, thanks for the reminder!

@Sriep the request pattern used by explorer / js-client-sdk is:

`https://test.0chain.net/proxy/publicEncryptionKey?client_json={"client_id":"2e67dbc4ee0559c920fd0cf6c021f8cfc72bc363e09e1adb5b4d8ccf7b30be6d","client_key":"7a25f90dc9916ec504b3a894f94f728217cdd630d5e7fc16b75b8230c9c381247b51d576409f3b2bb9b7fab746a460dca52f9686e772ab6fbd8421c7d364f496","keys":[{"public_key":"7a25f90dc9916ec504b3a894f94f728217cdd630d5e7fc16b75b8230c9c381247b51d576409f3b2bb9b7fab746a460dca52f9686e772ab6fbd8421c7d364f496","private_key":"e3da9ad9926b7a0afb63a61706fe08e5fca7fa7665f1a403632ce5cb0151731d"}],"mnemonics":"comfort indicate version room present perfect gallery chalk produce proud jeans gym quit absurd maid aunt risk all host end ranch bomb narrow stairs","version":"1.0","date_created":"53791-11-07 05:42:44"}`

**Comment by Sriep** [comment] 2021-10-31 15:08
I do not think this is an 0chain issue. My suspicion is that this is handled locally by block explorer. Will close and move to block explorer unless there is an 0chian endpoint that is misbehaving?

**Comment by shaktals** [comment] 2021-10-31 15:22
I can reproduce the error via cli. For example, if you try to recover a wallet on `dev` network, using a mnemonic from a wallet created on `huawei` network, it will succeed. But it should not.

**Comment by Sriep** [comment] 2021-10-31 15:25
I think this operation is done locally in block explorer and zwalletcli. Why do you need 0chain to recover a wallet from a secret phrase? Anyway, are you ok to move this issue to zwalletcli and block-explorer.

What command did you use on zwalletcli?

**Comment by shaktals** [comment] 2021-10-31 15:27
./zwallet recoverwallet

**Comment by shaktals** [comment] 2021-10-31 15:38
I just noticed that when recovering/restoring a wallet on explorer, it uses the `js-client-sdk`restoreWallet method.
But, that method in turn calls `createWallet` passing it the mnemonic, and recreating the keys/id from it.

So, we can't verify if a wallet with given mnemonic already exists?
If yes, that's ok. It is not a major needed feature.

**Comment by shaktals** [comment] 2021-11-16 18:10
> So, we can't verify if a wallet with given mnemonic already exists? If yes, that's ok. It is not a major needed feature.

@Sriep can you confirm the above? Upon your answer we can close the issue.

**Comment by shaktals** [comment] 2021-11-24 00:02
It seems that for now we don't have a way to confirm if a wallet exists or not.
What maybe could work is to check if there is any transaction with the walletId on the blockchain.
I'll close this issue and open a [discussion on slack](https://0chain.slack.com/archives/G01FYNN6DK4/p1637712120114900).

**Closed as completed by shaktals** 2021-11-24 00:02 UTC
