### ISSUE TITLE
Event db. Improve remove duplicates.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#799] opened 2021-12-20 11:35 UTC
We want to avoid acting on the same event twice. The current method, [removeDuplicate](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/event.go#L75), is inefficient as it queries all events. 

Especially in conjunction with https://github.com/0chain/0chain/issues/756 we can assume that blocks will not be repeated. So we should only need to search events for one block for repeats.

**Comment by dabasov** [comment] 2021-12-30 10:57
`Count()` can slow down the query as it adds `count(*)`, in general count is bad for exist, since it is aggregation function. afaik the best way to check existence is something like
```
select exists(select 1 from events where tx_hash = ? AND index = ?)
```
it is possible to execute raw queries in gorm, something like this
```
db.Raw("select exists(select 1 from events where tx_hash = ? AND index = ?) as ex", hash, index).Scan(&Ex)
```
cc @samtholiya

**Comment by samtholiya** [comment] 2021-12-31 12:23
Optimized the query. So the issue is partially solved :) 
As discussed with @kushthedude there are issues that are required to be solved before solving this issue.

**Comment by dabasov** [comment] 2022-01-01 14:14
btw, I added `context.Context` to the queries, so they are now cancellable

**Comment by samtholiya** [comment] 2022-01-01 18:26
@dabasov so you want me to add `context.Context` to the query is what I understand. Is that right?

**Comment by Sriep** [comment] 2022-01-02 11:18
The main point here is that we do not need to search all the events, only the ones for the current block. This is what is causing problems that have been reported.

We can rely on other mechanisms to ensure there are no repeat events spread across multiple rounds, and event db only get the events for a round once.

**Comment by dabasov** [comment] 2022-01-02 13:26
@samtholiya no, I've added it already, it should be merged to staging soon. we can cherry-pick this commit is you need

**Closed as completed** 2022-02-19 09:10 UTC
Labels: bug, Event database
