### ISSUE TITLE
Unstake tokens is returning success response in case of allocation size = staked capacity

### ISSUE THREAD

**Issue by Jayashsatolia403** [0chain/0chain#2268] opened 2023-04-04 17:02 UTC
When allocation Size is equal to delegate capacity, tokens are not getting unstaked as expected but the unstake tokens response is successful.

**Comment by Kishan-Dhakan** [comment] 2023-04-04 18:31
Please add steps to reproduce, what is expected and what is happening.

**Comment by Jayashsatolia403** [comment] 2023-04-04 18:36
Sure.

Network : 6 blobber 6 validator
Stakes  : 1 zcn each
Allocation : 3 data | 3 parity | 30GB allocaiton (equal to staked capacity)

Then I am trying to unstake the tokens. The response of this request is success but no tokens are unstaked here (as expected). 

We want to return an error when we can't unstake the tokens instead of success even in the case of failure.

**Comment by Sriep** [comment] 2023-04-19 11:18
I believe this was by design. If the [total staked is less than the required balance](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L158), then we add the balance to the total we wish to unstake and return with no tokens unstaked. 
```go
	if staked < requiredBalance {
		if dp.Status != spenum.Unstaking {
			totalUnStake, err := currency.AddCoin(sp.TotalUnStake, dp.Balance)
			if err != nil {
				return err
			}
			//we are locking current pool and hold the tokens, they won't be counted in clean stake after that
			sp.TotalUnStake = totalUnStake

			dp.Status = spenum.Unstaking
		}
		return nil
	}
```
The transaction does not fail because the endpoint wants to update [TotalUnStake](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L53) and this would not happen if there was an error.

We might want to consider changing this. I believe the idea of [TotalUnStake](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/stakepool.go#L53) is that we prevent taking on new allocation backed using tokens someone is trying to unstake. However, as someone can repeatedly send `stake_pool_unlock` transactions, we should have some memory of who attempting unstaking tokens for this to make sense (Otherwise someone could do a DOS attack on a blobber). The easiest thing would be to remove this functionality altogether.

**Comment by Sriep** [comment] 2023-04-20 08:21
Closing as there is no bug. We can revisit if we want to alter how this functionality works in a separate issue.

**Closed as completed by Sriep** 2023-04-20 08:21 UTC
