### ISSUE TITLE
Panic on processing event of Tag 25

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#2330] opened 2023-04-26 06:10 UTC
`
ERROR	event/process.go:347	panic recovered in processEvent	{"r": "runtime error: index out of range [5] with length 1", "event": {"ID":288316,"CreatedAt":"2023-04-26T02:24:52.399955204Z","block_number":20586,"tx_hash":"","type":3,"tag":25,"index":"112929333f4a023a28f5e5b4e8f729c87d00a8d00f2c01ab8428a5415b6a0bbf","data":[{"provider_id":"95bfb9bf23c9ffb6fdaa002bedc10c598a7e6cba8db0a61825f64c1d92d880f0","provider_type":4,"reward":28182,"reward_type":7,"delegate_rewards":{},"delegate_penalties":null},{"provider_id":"133e219980274d85144e7c0165d633584f53263a93e44eba8839452a7148e0ad","provider_type":4,"reward":119277,"reward_type":7,"delegate_rewards":{"5da4f729b4dc8eac33eaa997614bc9366bd3ca8f122cd4016ab77350ad98d6ba":92771,"bb265569857a68bdafdab0123cbcb4274fbb1dd8ee86d7cd51ea91c347ef6b23":92771,"ef6dc5733fe7432b48701ca5709458d0ff38e77c54813ae78e8af24eafb40bf0":92771},"delegate_penalties":null},{"provider_id":"73ad5727612116c025bb4405bf3adb4a4a04867ae508c51cf885395bffc8a949","provider_type":1,"reward":0,"reward_type":4,"delegate_rewards":{"07990ef12dcdd2c40fd10423b91426d6a2713e3e75417a936e92901bf1456e33":3520000000},"delegate_penalties":null},{"provider_id":"30001a01a888584772b7fee13934021ab8557e0ed471c0a3a454e9164180aef1","provider_type":2,"reward":924000000,"reward_type":6,"delegate_rewards":{"f9d2a77f966cc72dd4a1743ade45cf94e249946db4e9cfdfe6e1b9b751096e73":8316000000},"delegate_penalties":null},{"provider_id":"97e9cdb146e29d863a71261e5625fb0d1af4788d578e01b5d28a0d250ca5bbfc","provider_type":4,"reward":28181,"reward_type":7,"delegate_rewards":{},"delegate_penalties":null},{"provider_id":"6066ef97b8d7eb0ae2bee9f9669dadcffa8a0b12ec89cbbe679467dbba84f865","provider_type":3,"reward":3101206,"reward_type":9,"delegate_rewards":{"065fea8c5d8ebc6d6cacef326fd200f153a5b19a1079ebb1015d87c23ed1d5ce":13955432,"8515be4e2d7c0feaade0283062da8decf139f7360b3f18118f3b1651a44d4b6b":13955431},"delegate_penalties":null},{"provider_id":"e77872ee40afd02fe4873a057c212e768c5efd26280a6b8a8afc9375ba7b09c8","provider_type":3,"reward":219817,"reward_type":9,"delegate_rewards":{"065fea8c5d8ebc6d6cacef326fd200f153a5b19a1079ebb1015d87c23ed1d5ce":1978356},"delegate_penalties":null},{"provider_id":"ea26431f8adb7061766f1d6bbcc3b292d70dd59960d857f04b8a75e6a5bbe04f","provider_type":2,"reward":0,"reward_type":2,"delegate_rewards":{"542d9bd9e0452fa84f7ffd2f529b8db8eaa4817c378630b64121bf9e6da5b1f3":285600000},"delegate_penalties":null},{"provider_id":"9462ad82b0684f018a31c595ce19b75427b14a33ca72c1c5bba7cee43ed8f0c7","provider_type":4,"reward":397591,"reward_type":7,"delegate_rewards":{},"delegate_penalties":null},{"provider_id":"73ad5727612116c025bb4405bf3adb4a4a04867ae508c51cf885395bffc8a949","provider_type":1,"reward":0,"reward_type":1,"delegate_rewards":{"07990ef12dcdd2c40fd10423b91426d6a2713e3e75417a936e92901bf1456e33":108800000},"delegate_penalties":null},{"provider_id":"ea26431f8adb7061766f1d6bbcc3b292d70dd59960d857f04b8a75e6a5bbe04f","provider_type":2,"reward":0,"reward_type":6,"delegate_rewards":{"542d9bd9e0452fa84f7ffd2f529b8db8eaa4817c378630b64121bf9e6da5b1f3":9240000000},"delegate_penalties":null},{"provider_id":"30001a01a888584772b7fee13934021ab8557e0ed471c0a3a454e9164180aef1","provider_type":2,"reward":28560000,"reward_type":2,"delegate_rewards":{"f9d2a77f966cc72dd4a1743ade45cf94e249946db4e9cfdfe6e1b9b751096e73":257040000},"delegate_penalties":null}]}}
`

**Comment by devyetii** [comment] 2023-05-07 22:12
@peterlimg I couldn't reproduce that, I added some unit tests with the same payload up there to test the two main functions called by `TagStakePoolReward` and both worked fine with no panics. Can you please provide a stack trace of the error if available, or steps to reproduce.

**Comment by devyetii** [comment] 2023-05-07 22:42
Even tested `processEvent()` with the same event payload as above and got successful run.

**Comment by devyetii** [comment] 2023-05-07 22:45
This is related to an issue fixed before in this [merged PR](https://github.com/0chain/0chain/pull/2325), it was merged the same day 7-8 hours after this issue was opened.

**Closed as completed by devyetii** 2023-05-07 22:45 UTC
Labels: bug
