### ISSUE TITLE
Blobbers get deregister due to the health check events failure

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#1981] opened 2023-01-10 10:43 UTC
Blobbers might be marked as offline after running for a while due to the error shown below, that's why system test case `TestBlobberConfigUpdate` failed, because it could not find any blobbers.

```sh
2023-01-10T10:37:11.578Z        ERROR   event/process.go:192    error processing event  {"round": 2679, "tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blob
bers\" violates not-null constraint (SQLSTATE 23502)"}
2023-01-10T10:37:12.619Z        ERROR   event/process.go:278    addStat typeStats error {"round": 2684, "block": "5b201e08b81615ac1de309af40395f6216721d47d2466c78862405301308ae3a", "block size": 3, "event t
ype": "TagUpdateBlobberAllocatedHealth", "event tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blobbers\" violates not-null constraint (SQLSTATE 23502)"}
2023-01-10T10:37:12.619Z        ERROR   event/process.go:319    event could not be processed    {"round": 2684, "block": "5b201e08b81615ac1de309af40395f6216721d47d2466c78862405301308ae3a", "block size": 3,
"event type": "TagUpdateBlobberAllocatedHealth", "event tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blobbers\" violates not-null constraint (SQLSTATE 235
02)"}
2023-01-10T10:37:12.619Z        ERROR   event/process.go:192    error processing event  {"round": 2684, "tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blob
bers\" violates not-null constraint (SQLSTATE 23502)"}
2023-01-10T10:37:14.704Z        ERROR   event/process.go:278    addStat typeStats error {"round": 2694, "block": "7c4cf77b98d2fd7deee3af795e943ac90f4b1462220fbcc44e08a863913df8d7", "block size": 3, "event t
ype": "TagUpdateBlobberAllocatedHealth", "event tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blobbers\" violates not-null constraint (SQLSTATE 23502)"}
2023-01-10T10:37:14.704Z        ERROR   event/process.go:319    event could not be processed    {"round": 2694, "block": "7c4cf77b98d2fd7deee3af795e943ac90f4b1462220fbcc44e08a863913df8d7", "block size": 3,
"event type": "TagUpdateBlobberAllocatedHealth", "event tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blobbers\" violates not-null constraint (SQLSTATE 235
02)"}
2023-01-10T10:37:14.704Z        ERROR   event/process.go:192    error processing event  {"round": 2694, "tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blob
bers\" violates not-null constraint (SQLSTATE 23502)"}
2023-01-10T10:37:16.169Z        ERROR   event/process.go:278    addStat typeStats error {"round": 2701, "block": "c2700dfbdd38e146f43cca6db369708746dce3a7061510519e1c33c6614b080c", "block size": 3, "event t
ype": "TagUpdateBlobberAllocatedHealth", "event tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blobbers\" violates not-null constraint (SQLSTATE 23502)"}
2023-01-10T10:37:16.169Z        ERROR   event/process.go:319    event could not be processed    {"round": 2701, "block": "c2700dfbdd38e146f43cca6db369708746dce3a7061510519e1c33c6614b080c", "block size": 3,
"event type": "TagUpdateBlobberAllocatedHealth", "event tag": "TagBlobberHealthCheck", "error": "ERROR: null value in column \"bucket_id\" of relation \"blobbers\" violates not-null constraint (SQLSTATE 23$
```

**Comment by devyetii** [comment] 2023-01-10 11:14
Must be related to #1933 which I was working on. I'll check and fix

**Comment by devyetii** [comment] 2023-01-10 11:26
Also this is related to the fact that we usually use create with conflict for updates in events_db. This issue will be addressed in #1927

**Comment by devyetii** [comment] 2023-01-10 16:10
It's worth mentioning that upsert should work fine since all the blobbers should be stored in the db. The problem is that the blobber which sends health check is not found in the db. The upsert problem will be solved when the updater is used instead and I'll add a fast workaround. However, we'll still need to investigate why the blobber sending health check is not found in events db.

**Comment by peterlimg** [comment] 2023-01-11 02:33
@devyetii yes, we need to know why the blobber is not in the db when sending health check, otherwise the updater will fail too as we can't update items that do not exist, right?

**Comment by peterlimg** [comment] 2023-01-11 04:16
The error as shown above actually gives us the info that gorm will fail on doing upsert with `none null` field, which is the `bucket_id` column. So what we need to do to fix this is simply set the `bucket_id` to the value it is. and I think we should have this kind of error of all the `upsert` actions that has `none null` constraint, especially for those type embeded `Provider` struct.

**Comment by devyetii** [comment] 2023-01-11 05:03
I was facing some problems with my local machine that's why I couldn't submit code. If you didn't include it in any PR you're working on let me do the fix as I was working on the same parts of the code in #1933  @peterlimg.

**Closed as completed** 2023-01-12 06:29 UTC
Labels: bug
